/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   D:\Documents\Code\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -ID:\Documents\Code\nim-0.18.0\lib -o d:\Documents\SourceTree\Challenges\Nim\nimcache\dp.o d:\Documents\SourceTree\Challenges\Nim\nimcache\dp.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ tySequence_PSP8snSsRoFs9cDiya9bd7UQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NI x, NI y, void* ClE_0);
void* ClE_0;
} tyProc_fDD7zVPPl59bNBu4ChTEQeQ;
typedef NU8 tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA;
typedef N_CLOSURE_PTR(NI, TM_PTsAkc9aqUDy0s9bu67MiKNQ_31) (NI x, NI y, void* ClE_0);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ {
  TGenericSeq Sup;
  tySequence_qwqHTkRvwhrRyENtudHQ7g* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, fib_spVJw8IKs8b60zSCYaL9bLA)(NI n);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, ways_to_sum_4UcLeqMlV9bHmAFwb0AgK2A)(NI target, NI* nums, NI numsLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, tiling_spVJw8IKs8b60zSCYaL9bLA_2)(NI n);
N_LIB_PRIVATE N_NIMCALL(NI, binomial_coeff_m6HiyThWbGGCvtv9cFISeDg)(NI n, NI k);
N_LIB_PRIVATE N_NIMCALL(tySequence_PSP8snSsRoFs9cDiya9bd7UQ*, newSeq_jCuaP8Qsj9a7G1PJ9aNE4s5Q)(NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NI, largest_divisible_pairs_RLGd16gFtHz77M9bLPjlzUA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** elems);
N_LIB_PRIVATE N_NIMCALL(void, sort_84EnBzTXl9c1maQcyvYsKBQ)(NI* a, NI aLen_0, tyProc_fDD7zVPPl59bNBu4ChTEQeQ cmp, tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_8Eruo47qvrfENwO9aWPZfBQ_3)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__H9byP9au7Ewl1LWJ70fLKs7Q)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x);
N_LIB_PRIVATE N_NIMCALL(NI, max_31akPHXxtg88erifwmmCyA)(NI* x, NI xLen_0);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_PTsAkc9aqUDy0s9bu67MiKNQ_37)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, merge_3YlxpxWbu7ggyWNi6G1FdQ)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI lo, NI m, NI hi, tyProc_fDD7zVPPl59bNBu4ChTEQeQ cmp, tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString_KntgA0rM9cu9bcqGqe2CjUEQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, dpDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
tySequence_qwqHTkRvwhrRyENtudHQ7g* pairs_vccII8Z4Eb44KjqIHmF9bKA;
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_7, "Fibonacci 30: ", 14);
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_13, "Number of ways to sum 8 with [1, 3, 5]: ", 40);
NIM_CONST tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw TM_PTsAkc9aqUDy0s9bu67MiKNQ_14 = {((NI) 1),
((NI) 3),
((NI) 5)}
;
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_20, "Tiling board of size 4: ", 24);
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_30, "Binomial coefficient for n = 5, k = 2: ", 39);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[5];
} TM_PTsAkc9aqUDy0s9bu67MiKNQ_39 = {{5, 5}, {((NI) 10),
((NI) 5),
((NI) 3),
((NI) 15),
((NI) 20)}};
NIM_CONST tySequence_qwqHTkRvwhrRyENtudHQ7g* TM_PTsAkc9aqUDy0s9bu67MiKNQ_38 = ((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_PTsAkc9aqUDy0s9bu67MiKNQ_39);
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_40, "Largest divisible pairs of [10, 5, 3, 15, 20]: ", 47);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[6];
} TM_PTsAkc9aqUDy0s9bu67MiKNQ_42 = {{6, 6}, {((NI) 18),
((NI) 1),
((NI) 3),
((NI) 6),
((NI) 13),
((NI) 17)}};
NIM_CONST tySequence_qwqHTkRvwhrRyENtudHQ7g* TM_PTsAkc9aqUDy0s9bu67MiKNQ_41 = ((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_PTsAkc9aqUDy0s9bu67MiKNQ_42);
STRING_LITERAL(TM_PTsAkc9aqUDy0s9bu67MiKNQ_43, "Largest divisible pairs of [18, 1, 3, 6, 13, 17]: ", 50);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, fib_spVJw8IKs8b60zSCYaL9bLA)(NI n) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* dp;
	NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_2;
	nimfr_("fib", "dp.nim");
{	result = (NI)0;
	nimln_(4, "dp.nim");
	TM_PTsAkc9aqUDy0s9bu67MiKNQ_2 = addInt(n, ((NI) 1));
	dp = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_2), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	if ((NU)(((NI) 0)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(5, "dp.nim");
	dp->data[((NI) 0)] = ((NI) 0);
	if ((NU)(((NI) 1)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(6, "dp.nim");
	dp->data[((NI) 1)] = ((NI) 1);
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 2);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_3;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_4;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_5;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_6;
				if (!(res <= n)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				if ((NU)(i) >= (NU)(dp->Sup.len)) raiseIndexError();
				nimln_(8, "dp.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_3 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_3)) >= (NU)(dp->Sup.len)) raiseIndexError();
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_4 = subInt(i, ((NI) 2));
				if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_4)) >= (NU)(dp->Sup.len)) raiseIndexError();
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_5 = addInt(dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_3)], dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_4)]);
				dp->data[i] = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_5);
				nimln_(2048, "system.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_6 = addInt(res, ((NI) 1));
				res = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_6);
			} LA3: ;
		}
	}
	nimln_(9, "dp.nim");
	if ((NU)(n) >= (NU)(dp->Sup.len)) raiseIndexError();
	result = dp->data[n];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, ways_to_sum_4UcLeqMlV9bHmAFwb0AgK2A)(NI target, NI* nums, NI numsLen_0) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* dp;
	NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_8;
	nimfr_("ways_to_sum", "dp.nim");
{	result = (NI)0;
	nimln_(18, "dp.nim");
	TM_PTsAkc9aqUDy0s9bu67MiKNQ_8 = addInt(target, ((NI) 1));
	dp = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_8), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	if ((NU)(((NI) 0)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(19, "dp.nim");
	dp->data[((NI) 0)] = ((NI) 1);
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_12;
				if (!(res <= target)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				{
					NI j;
					NI colontmp_;
					NI res_2;
					j = (NI)0;
					colontmp_ = (NI)0;
					nimln_(21, "dp.nim");
					colontmp_ = (numsLen_0-1);
					nimln_(2045, "system.nim");
					res_2 = ((NI) 0);
					{
						nimln_(2046, "system.nim");
						while (1) {
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_11;
							if (!(res_2 <= colontmp_)) goto LA6;
							nimln_(2047, "system.nim");
							j = res_2;
							nimln_(22, "dp.nim");
							{
								NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_9;
								NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_10;
								if ((NU)(j) >= (NU)(numsLen_0)) raiseIndexError();
								if (!(nums[j] <= i)) goto LA9_;
								nimln_(23, "dp.nim");
								if ((NU)(i) >= (NU)(dp->Sup.len)) raiseIndexError();
								if ((NU)(j) >= (NU)(numsLen_0)) raiseIndexError();
								TM_PTsAkc9aqUDy0s9bu67MiKNQ_9 = subInt(i, nums[j]);
								if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_9)) >= (NU)(dp->Sup.len)) raiseIndexError();
								TM_PTsAkc9aqUDy0s9bu67MiKNQ_10 = addInt(dp->data[i], dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_9)]);
								dp->data[i] = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_10);
							}
							LA9_: ;
							nimln_(2048, "system.nim");
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_11 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_11);
						} LA6: ;
					}
				}
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_12 = addInt(res, ((NI) 1));
				res = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_12);
			} LA3: ;
		}
	}
	nimln_(24, "dp.nim");
	if ((NU)(target) >= (NU)(dp->Sup.len)) raiseIndexError();
	result = dp->data[target];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, tiling_spVJw8IKs8b60zSCYaL9bLA_2)(NI n) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* dp;
	NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_19;
	nimfr_("tiling", "dp.nim");
{	result = (NI)0;
	nimln_(32, "dp.nim");
	{
		if (!(n <= ((NI) 2))) goto LA3_;
		nimln_(33, "dp.nim");
		result = n;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(34, "dp.nim");
	dp = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(n, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	if ((NU)(((NI) 0)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(35, "dp.nim");
	dp->data[((NI) 0)] = ((NI) 1);
	if ((NU)(((NI) 1)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(36, "dp.nim");
	dp->data[((NI) 1)] = ((NI) 2);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 2);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_15;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_16;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_17;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_18;
				if (!(i_2 < n)) goto LA7;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) >= (NU)(dp->Sup.len)) raiseIndexError();
				nimln_(38, "dp.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_15 = subInt(i, ((NI) 1));
				if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_15)) >= (NU)(dp->Sup.len)) raiseIndexError();
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_16 = subInt(i, ((NI) 2));
				if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_16)) >= (NU)(dp->Sup.len)) raiseIndexError();
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_17 = addInt(dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_15)], dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_16)]);
				dp->data[i] = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_17);
				nimln_(3522, "system.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_18 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_18);
			} LA7: ;
		}
	}
	nimln_(39, "dp.nim");
	TM_PTsAkc9aqUDy0s9bu67MiKNQ_19 = subInt(n, ((NI) 1));
	if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_19)) >= (NU)(dp->Sup.len)) raiseIndexError();
	result = dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_19)];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, binomial_coeff_m6HiyThWbGGCvtv9cFISeDg)(NI n, NI k) {
	NI result;
	tySequence_PSP8snSsRoFs9cDiya9bd7UQ* dp;
	nimfr_("binomial_coeff", "dp.nim");
{	result = (NI)0;
	nimln_(46, "dp.nim");
	dp = newSeq_jCuaP8Qsj9a7G1PJ9aNE4s5Q(((NI) 0));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_21;
				tySequence_qwqHTkRvwhrRyENtudHQ7g* T4_;
				NI T5_;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_22;
				if (!(res <= n)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(48, "dp.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_21 = addInt(k, ((NI) 1));
				T4_ = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
				T4_ = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_21), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				dp = (tySequence_PSP8snSsRoFs9cDiya9bd7UQ*) incrSeqV2(&(dp)->Sup, sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*));
				T5_ = dp->Sup.len++;
				genericSeqAssign((&dp->data[T5_]), T4_, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
				nimln_(2048, "system.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_22 = addInt(res, ((NI) 1));
				res = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_22);
			} LA3: ;
		}
	}
	{
		NI i_2;
		NI res_2;
		i_2 = (NI)0;
		nimln_(2045, "system.nim");
		res_2 = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_23;
				if (!(res_2 <= n)) goto LA8;
				nimln_(2047, "system.nim");
				i_2 = res_2;
				if ((NU)(i_2) >= (NU)(dp->Sup.len)) raiseIndexError();
				if ((NU)(((NI) 0)) >= (NU)(dp->data[i_2]->Sup.len)) raiseIndexError();
				nimln_(50, "dp.nim");
				dp->data[i_2]->data[((NI) 0)] = ((NI) 1);
				nimln_(2048, "system.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_23 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_23);
			} LA8: ;
		}
	}
	{
		NI i_3;
		NI res_3;
		i_3 = (NI)0;
		nimln_(2045, "system.nim");
		res_3 = ((NI) 1);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_29;
				if (!(res_3 <= n)) goto LA11;
				nimln_(2047, "system.nim");
				i_3 = res_3;
				{
					NI j;
					NI res_4;
					j = (NI)0;
					nimln_(2045, "system.nim");
					res_4 = ((NI) 1);
					{
						nimln_(2046, "system.nim");
						while (1) {
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_24;
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_25;
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_26;
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_27;
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_28;
							if (!(res_4 <= k)) goto LA14;
							nimln_(2047, "system.nim");
							j = res_4;
							if ((NU)(i_3) >= (NU)(dp->Sup.len)) raiseIndexError();
							if ((NU)(j) >= (NU)(dp->data[i_3]->Sup.len)) raiseIndexError();
							nimln_(53, "dp.nim");
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_24 = subInt(i_3, ((NI) 1));
							if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_24)) >= (NU)(dp->Sup.len)) raiseIndexError();
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_25 = subInt(j, ((NI) 1));
							if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_25)) >= (NU)(dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_24)]->Sup.len)) raiseIndexError();
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_26 = subInt(i_3, ((NI) 1));
							if ((NU)((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_26)) >= (NU)(dp->Sup.len)) raiseIndexError();
							if ((NU)(j) >= (NU)(dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_26)]->Sup.len)) raiseIndexError();
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_27 = addInt(dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_24)]->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_25)], dp->data[(NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_26)]->data[j]);
							dp->data[i_3]->data[j] = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_27);
							nimln_(2048, "system.nim");
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_28 = addInt(res_4, ((NI) 1));
							res_4 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_28);
						} LA14: ;
					}
				}
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_29 = addInt(res_3, ((NI) 1));
				res_3 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_29);
			} LA11: ;
		}
	}
	nimln_(54, "dp.nim");
	if ((NU)(n) >= (NU)(dp->Sup.len)) raiseIndexError();
	if ((NU)(k) >= (NU)(dp->data[n]->Sup.len)) raiseIndexError();
	result = dp->data[n]->data[k];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, largest_divisible_pairs_RLGd16gFtHz77M9bLPjlzUA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** elems) {
	NI result;
	tyProc_fDD7zVPPl59bNBu4ChTEQeQ T1_;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* dp;
	NI T2_;
	NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_32;
	tyArray_nHXaesL0DJZHyVS07ARPRA T14_;
	nimfr_("largest_divisible_pairs", "dp.nim");
{	result = (NI)0;
	nimln_(62, "dp.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_PTsAkc9aqUDy0s9bu67MiKNQ_31) (cmp_8Eruo47qvrfENwO9aWPZfBQ_3)); T1_.ClE_0 = NIM_NIL;
	sort_84EnBzTXl9c1maQcyvYsKBQ((*elems)->data, (*elems)->Sup.len, T1_, ((tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA) 0));
	nimln_(63, "dp.nim");
	T2_ = ((*elems) ? (*elems)->Sup.len : 0);
	TM_PTsAkc9aqUDy0s9bu67MiKNQ_32 = addInt(T2_, ((NI) 1));
	dp = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange((NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_32), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	if ((NU)(((NI) 0)) >= (NU)(dp->Sup.len)) raiseIndexError();
	nimln_(65, "dp.nim");
	dp->data[((NI) 0)] = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(67, "dp.nim");
		T4_ = ((*elems) ? (*elems)->Sup.len : 0);
		colontmp_ = T4_;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 1);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI max_elem;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_35;
				NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_36;
				if (!(i_2 < colontmp_)) goto LA6;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(68, "dp.nim");
				max_elem = ((NI) 0);
				{
					NI j;
					NI colontmp__2;
					NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_33;
					NI res;
					j = (NI)0;
					colontmp__2 = (NI)0;
					nimln_(69, "dp.nim");
					TM_PTsAkc9aqUDy0s9bu67MiKNQ_33 = subInt(i, ((NI) 1));
					colontmp__2 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_33);
					nimln_(2015, "system.nim");
					res = colontmp__2;
					{
						nimln_(2016, "system.nim");
						while (1) {
							NI TM_PTsAkc9aqUDy0s9bu67MiKNQ_34;
							nimln_(69, "dp.nim");
							if (!(((NI) 0) <= res)) goto LA9;
							nimln_(2017, "system.nim");
							j = res;
							nimln_(70, "dp.nim");
							{
								if ((NU)(j) >= (NU)((*elems)->Sup.len)) raiseIndexError();
								if ((NU)(i) >= (NU)((*elems)->Sup.len)) raiseIndexError();
								if (!((NI)((NU64)((*elems)->data[j]) % (NU64)((*elems)->data[i])) == ((NI) 0))) goto LA12_;
								nimln_(71, "dp.nim");
								if ((NU)(j) >= (NU)(dp->Sup.len)) raiseIndexError();
								max_elem = ((max_elem >= dp->data[j]) ? max_elem : dp->data[j]);
							}
							LA12_: ;
							nimln_(2018, "system.nim");
							TM_PTsAkc9aqUDy0s9bu67MiKNQ_34 = subInt(res, ((NI) 1));
							res = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_34);
						} LA9: ;
					}
				}
				if ((NU)(i) >= (NU)(dp->Sup.len)) raiseIndexError();
				nimln_(72, "dp.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_35 = addInt(max_elem, ((NI) 1));
				dp->data[i] = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_35);
				nimln_(3522, "system.nim");
				TM_PTsAkc9aqUDy0s9bu67MiKNQ_36 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_PTsAkc9aqUDy0s9bu67MiKNQ_36);
			} LA6: ;
		}
	}
	nimln_(73, "dp.nim");
	memset((void*)T14_, 0, sizeof(T14_));
	T14_[0] = dollar__H9byP9au7Ewl1LWJ70fLKs7Q(dp);
	echoBinSafe(T14_, 1);
	nimln_(74, "dp.nim");
	result = max_31akPHXxtg88erifwmmCyA(dp->data, dp->Sup.len);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_PTsAkc9aqUDy0s9bu67MiKNQ_37)(void) {
	nimGCvisit((void*)pairs_vccII8Z4Eb44KjqIHmF9bKA, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_algorithmDatInit000();
	dpDatInit000();
	stdlib_algorithmInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	NI T2_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T3_;
	NI T4_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T5_;
	NI T6_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T7_;
	NI T8_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T9_;
	NI T10_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T11_;
	NI T12_;
	nimfr_("dp", "dp.nim");
nimRegisterGlobalMarker(TM_PTsAkc9aqUDy0s9bu67MiKNQ_37);
	nimln_(11, "dp.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_7));
	T2_ = (NI)0;
	T2_ = fib_spVJw8IKs8b60zSCYaL9bLA(((NI) 30));
	T1_[1] = nimIntToStr(T2_);
	echoBinSafe(T1_, 2);
	nimln_(26, "dp.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_13));
	T4_ = (NI)0;
	T4_ = ways_to_sum_4UcLeqMlV9bHmAFwb0AgK2A(((NI) 8), TM_PTsAkc9aqUDy0s9bu67MiKNQ_14, 3);
	T3_[1] = nimIntToStr(T4_);
	echoBinSafe(T3_, 2);
	nimln_(41, "dp.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T5_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_20));
	T6_ = (NI)0;
	T6_ = tiling_spVJw8IKs8b60zSCYaL9bLA_2(((NI) 4));
	T5_[1] = nimIntToStr(T6_);
	echoBinSafe(T5_, 2);
	nimln_(56, "dp.nim");
	memset((void*)T7_, 0, sizeof(T7_));
	T7_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_30));
	T8_ = (NI)0;
	T8_ = binomial_coeff_m6HiyThWbGGCvtv9cFISeDg(((NI) 8), ((NI) 2));
	T7_[1] = nimIntToStr(T8_);
	echoBinSafe(T7_, 2);
	nimln_(76, "dp.nim");
	genericSeqAssign((&pairs_vccII8Z4Eb44KjqIHmF9bKA), TM_PTsAkc9aqUDy0s9bu67MiKNQ_38, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	nimln_(77, "dp.nim");
	memset((void*)T9_, 0, sizeof(T9_));
	T9_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_40));
	T10_ = (NI)0;
	T10_ = largest_divisible_pairs_RLGd16gFtHz77M9bLPjlzUA((&pairs_vccII8Z4Eb44KjqIHmF9bKA));
	T9_[1] = nimIntToStr(T10_);
	echoBinSafe(T9_, 2);
	nimln_(78, "dp.nim");
	genericSeqAssign((&pairs_vccII8Z4Eb44KjqIHmF9bKA), TM_PTsAkc9aqUDy0s9bu67MiKNQ_41, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	nimln_(79, "dp.nim");
	memset((void*)T11_, 0, sizeof(T11_));
	T11_[0] = copyString(((NimStringDesc*) &TM_PTsAkc9aqUDy0s9bu67MiKNQ_43));
	T12_ = (NI)0;
	T12_ = largest_divisible_pairs_RLGd16gFtHz77M9bLPjlzUA((&pairs_vccII8Z4Eb44KjqIHmF9bKA));
	T11_[1] = nimIntToStr(T12_);
	echoBinSafe(T11_, 2);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, dpDatInit000)(void) {
}

