/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   D:\Documents\Code\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -ID:\Documents\Code\nim-0.18.0\lib -o d:\Documents\SourceTree\Challenges\Nim\nimcache\exponentiation.o d:\Documents\SourceTree\Challenges\Nim\nimcache\exponentiation.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, exponent_binary_npqi4kJ7015vhjS4gHyImQ)(NI* n, NI* x);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation)(NI* x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, mult_mat_hwXi2iCY9aewz7k7VmACdVQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, tySequence_qwqHTkRvwhrRyENtudHQ7g* y);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, pow_mat_aW2IER2BZmu1vkPYlXWjfA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** n, NI* x);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NI, fib_matrix_exp_UTOuZwP23azkd3lRnY9aWRg)(NI n);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__H9byP9au7Ewl1LWJ70fLKs7Q)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString_KntgA0rM9cu9bcqGqe2CjUEQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, exponentiationDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
NI x_4lJzM9awleS2bOq9bPStf9bpw;
NI y_M4Xr9cr2hdldN4ghM59b0i3g;
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[4];
} TM_3QZA9aYngBryeZ5dBpvXr9cw_27 = {{4, 4}, {((NI) 1),
((NI) 1),
((NI) 1),
((NI) 0)}};
NIM_CONST tySequence_qwqHTkRvwhrRyENtudHQ7g* TM_3QZA9aYngBryeZ5dBpvXr9cw_26 = ((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_3QZA9aYngBryeZ5dBpvXr9cw_27);
NIM_CONST struct {
  TGenericSeq Sup;
  NI data[2];
} TM_3QZA9aYngBryeZ5dBpvXr9cw_29 = {{2, 2}, {((NI) 1),
((NI) 0)}};
NIM_CONST tySequence_qwqHTkRvwhrRyENtudHQ7g* TM_3QZA9aYngBryeZ5dBpvXr9cw_28 = ((tySequence_qwqHTkRvwhrRyENtudHQ7g*)&TM_3QZA9aYngBryeZ5dBpvXr9cw_29);

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation)(NI* x, NI y) {
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_4;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_3QZA9aYngBryeZ5dBpvXr9cw_4 = mulInt((*x), y);
	(*x) = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_4);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, exponent_binary_npqi4kJ7015vhjS4gHyImQ)(NI* n, NI* x) {
	NI result;
	NI res;
	nimfr_("exponent_binary", "exponentiation.nim");
{	result = (NI)0;
	nimln_(2, "exponentiation.nim");
	{
		NI z;
		NI T5_;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_2;
		if (!((*x) < ((NI) 0))) goto LA3_;
		nimln_(3, "exponentiation.nim");
		if ((*x) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		z = ((NI64)-((*x)));
		nimln_(4, "exponentiation.nim");
		T5_ = (NI)0;
		T5_ = exponent_binary_npqi4kJ7015vhjS4gHyImQ(n, (&z));
		TM_3QZA9aYngBryeZ5dBpvXr9cw_2 = divInt(((NI) 1), T5_);
		result = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_2);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(5, "exponentiation.nim");
	res = ((NI) 1);
	{
		nimln_(6, "exponentiation.nim");
		while (1) {
			NI TM_3QZA9aYngBryeZ5dBpvXr9cw_5;
			if (!(((NI) 0) < (*x))) goto LA7;
			nimln_(7, "exponentiation.nim");
			{
				NI TM_3QZA9aYngBryeZ5dBpvXr9cw_3;
				TM_3QZA9aYngBryeZ5dBpvXr9cw_3 = modInt((*x), ((NI) 2));
				if (!((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_3) == ((NI) 1))) goto LA10_;
				nimln_(8, "exponentiation.nim");
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation((&res), (*n));
			}
			LA10_: ;
			nimln_(9, "exponentiation.nim");
			stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation(n, (*n));
			nimln_(10, "exponentiation.nim");
			TM_3QZA9aYngBryeZ5dBpvXr9cw_5 = divInt((*x), ((NI) 2));
			(*x) = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_5);
		} LA7: ;
	}
	nimln_(11, "exponentiation.nim");
	result = res;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, mult_mat_hwXi2iCY9aewz7k7VmACdVQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, tySequence_qwqHTkRvwhrRyENtudHQ7g* y) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	NI a;
	NI b;
	NI c;
	NI d;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_12;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_13;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_14;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_15;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_16;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_17;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_18;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_19;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_20;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_21;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_22;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_23;
	nimfr_("mult_mat", "exponentiation.nim");
{	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	a = (NI)0;
	b = (NI)0;
	c = (NI)0;
	d = (NI)0;
	nimln_(15, "exponentiation.nim");
	{
		NI T3_;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_6;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_7;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_8;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_9;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_10;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_11;
		T3_ = (y ? y->Sup.len : 0);
		if (!(T3_ == ((NI) 2))) goto LA4_;
		nimln_(16, "exponentiation.nim");
		if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_6 = mulInt(x->data[((NI) 0)], y->data[((NI) 0)]);
		if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_7 = mulInt(x->data[((NI) 1)], y->data[((NI) 1)]);
		TM_3QZA9aYngBryeZ5dBpvXr9cw_8 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_6), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_7));
		a = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_8);
		nimln_(17, "exponentiation.nim");
		if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_9 = mulInt(x->data[((NI) 2)], y->data[((NI) 0)]);
		if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_10 = mulInt(x->data[((NI) 3)], y->data[((NI) 1)]);
		TM_3QZA9aYngBryeZ5dBpvXr9cw_11 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_9), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_10));
		b = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_11);
		nimln_(18, "exponentiation.nim");
		result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 2);
		result->data[0] = a;
		result->data[1] = b;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(19, "exponentiation.nim");
	if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_12 = mulInt(x->data[((NI) 0)], y->data[((NI) 0)]);
	if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_13 = mulInt(x->data[((NI) 1)], y->data[((NI) 2)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_14 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_12), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_13));
	a = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_14);
	nimln_(20, "exponentiation.nim");
	if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_15 = mulInt(x->data[((NI) 0)], y->data[((NI) 1)]);
	if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_16 = mulInt(x->data[((NI) 1)], y->data[((NI) 3)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_17 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_15), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_16));
	b = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_17);
	nimln_(21, "exponentiation.nim");
	if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_18 = mulInt(x->data[((NI) 2)], y->data[((NI) 0)]);
	if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_19 = mulInt(x->data[((NI) 3)], y->data[((NI) 2)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_20 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_18), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_19));
	c = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_20);
	nimln_(22, "exponentiation.nim");
	if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_21 = mulInt(x->data[((NI) 2)], y->data[((NI) 1)]);
	if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_22 = mulInt(x->data[((NI) 3)], y->data[((NI) 3)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_23 = addInt((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_21), (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_22));
	d = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_23);
	nimln_(23, "exponentiation.nim");
	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 4);
	result->data[0] = a;
	result->data[1] = b;
	result->data[2] = c;
	result->data[3] = d;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, pow_mat_aW2IER2BZmu1vkPYlXWjfA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** n, NI* x) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* res;
	nimfr_("pow_mat", "exponentiation.nim");
{	result = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	res = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	nimln_(27, "exponentiation.nim");
	genericSeqAssign((&res), (*n), (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	{
		nimln_(28, "exponentiation.nim");
		while (1) {
			NI TM_3QZA9aYngBryeZ5dBpvXr9cw_25;
			if (!(((NI) 0) < (*x))) goto LA2;
			nimln_(29, "exponentiation.nim");
			{
				NI TM_3QZA9aYngBryeZ5dBpvXr9cw_24;
				TM_3QZA9aYngBryeZ5dBpvXr9cw_24 = modInt((*x), ((NI) 2));
				if (!((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_24) == ((NI) 1))) goto LA5_;
				nimln_(30, "exponentiation.nim");
				res = mult_mat_hwXi2iCY9aewz7k7VmACdVQ(res, (*n));
			}
			LA5_: ;
			nimln_(31, "exponentiation.nim");
			unsureAsgnRef((void**) (&(*n)), mult_mat_hwXi2iCY9aewz7k7VmACdVQ((*n), (*n)));
			nimln_(32, "exponentiation.nim");
			TM_3QZA9aYngBryeZ5dBpvXr9cw_25 = divInt((*x), ((NI) 2));
			(*x) = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_25);
		} LA2: ;
	}
	nimln_(33, "exponentiation.nim");
	genericSeqAssign((&result), res, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, fib_matrix_exp_UTOuZwP23azkd3lRnY9aWRg)(NI n) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* A;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* V;
	NI x;
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_30;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* res;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	nimfr_("fib_matrix_exp", "exponentiation.nim");
{	result = (NI)0;
	nimln_(37, "exponentiation.nim");
	genericSeqAssign((&A), TM_3QZA9aYngBryeZ5dBpvXr9cw_26, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	nimln_(38, "exponentiation.nim");
	genericSeqAssign((&V), TM_3QZA9aYngBryeZ5dBpvXr9cw_28, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
	nimln_(39, "exponentiation.nim");
	TM_3QZA9aYngBryeZ5dBpvXr9cw_30 = subInt(n, ((NI) 2));
	x = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_30);
	nimln_(40, "exponentiation.nim");
	T1_ = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	T1_ = pow_mat_aW2IER2BZmu1vkPYlXWjfA((&A), (&x));
	res = mult_mat_hwXi2iCY9aewz7k7VmACdVQ(T1_, V);
	nimln_(41, "exponentiation.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = dollar__H9byP9au7Ewl1LWJ70fLKs7Q(res);
	echoBinSafe(T2_, 1);
	nimln_(42, "exponentiation.nim");
	if ((NU)(((NI) 0)) >= (NU)(res->Sup.len)) raiseIndexError();
	result = res->data[((NI) 0)];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	exponentiationDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
	NI T4_;
	nimfr_("exponentiation", "exponentiation.nim");
	nimln_(44, "exponentiation.nim");
	x_4lJzM9awleS2bOq9bPStf9bpw = ((NI) 2);
	nimln_(45, "exponentiation.nim");
	y_M4Xr9cr2hdldN4ghM59b0i3g = ((NI) 3);
	nimln_(46, "exponentiation.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NI)0;
	T2_ = exponent_binary_npqi4kJ7015vhjS4gHyImQ((&x_4lJzM9awleS2bOq9bPStf9bpw), (&y_M4Xr9cr2hdldN4ghM59b0i3g));
	T1_[0] = nimIntToStr(T2_);
	echoBinSafe(T1_, 1);
	nimln_(47, "exponentiation.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	T4_ = (NI)0;
	T4_ = fib_matrix_exp_UTOuZwP23azkd3lRnY9aWRg(((NI) 9));
	T3_[0] = nimIntToStr(T4_);
	echoBinSafe(T3_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, exponentiationDatInit000)(void) {
NTI_qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*);
NTI_qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTI_qwqHTkRvwhrRyENtudHQ7g_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_qwqHTkRvwhrRyENtudHQ7g_.flags = 2;
NTI_qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g;
}

