/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\aisae\Documents\Dependencies\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\Users\aisae\Documents\Dependencies\nim-0.18.0\lib -o c:\Users\aisae\Documents\Sourcetree\Challenges\Nim\nimcache\exponentiation.o c:\Users\aisae\Documents\Sourcetree\Challenges\Nim\nimcache\exponentiation.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_IHUFRsFxZNv7YydiUO2esQ tySequence_IHUFRsFxZNv7YydiUO2esQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI64 tyArray_EawPLnQhPqWwYm5GdCoh8A[2];
typedef tyArray_EawPLnQhPqWwYm5GdCoh8A tyArray_X4Lo9adz49bWDIQMo8kGcUYA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence_IHUFRsFxZNv7YydiUO2esQ {
  TGenericSeq Sup;
  NI64 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, exponent_binary_eqKG4APkqy5I3XN2s41dNw)(NI* n, NI* x);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation)(NI* x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, mult_mat_seq_gAx9cw1jGr5nn9cG9bQNBHmSw)(tySequence_IHUFRsFxZNv7YydiUO2esQ* x, tySequence_IHUFRsFxZNv7YydiUO2esQ* y);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
static N_NIMCALL(void, Marker_tySequence_IHUFRsFxZNv7YydiUO2esQ)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, pow_mat_seq_r9aZSYkqxTNtselrdI83q7g)(tySequence_IHUFRsFxZNv7YydiUO2esQ** n, NI64* x);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NI64, modInt64)(NI64 a, NI64 b);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI64, divInt64)(NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI64, fib_matrix_exp_qSFrKVtQsOuIF1VV39aezJQ)(NI64 n);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, pow_mat_HdAB07TCTeuAOvGfbnUtNw)(tyArray_EawPLnQhPqWwYm5GdCoh8A* a, NI64* x, tyArray_X4Lo9adz49bWDIQMo8kGcUYA Result);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, mult_mat_TwUb3trnSFHi9aXPb9buA3iA)(tyArray_X4Lo9adz49bWDIQMo8kGcUYA a, tyArray_X4Lo9adz49bWDIQMo8kGcUYA b, tyArray_X4Lo9adz49bWDIQMo8kGcUYA Result);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, exponentiationDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
TNimType NTI_IHUFRsFxZNv7YydiUO2esQ_;
NI x_4lJzM9awleS2bOq9bPStf9bpw;
NI y_M4Xr9cr2hdldN4ghM59b0i3g;
STRING_LITERAL(TM_3QZA9aYngBryeZ5dBpvXr9cw_5, "n, x: ", 6);
STRING_LITERAL(TM_3QZA9aYngBryeZ5dBpvXr9cw_6, " ", 1);
NIM_CONST tyArray_X4Lo9adz49bWDIQMo8kGcUYA TM_3QZA9aYngBryeZ5dBpvXr9cw_28 = {{IL64(1),
IL64(1)}
,
{IL64(1),
IL64(0)}
}
;
STRING_LITERAL(TM_3QZA9aYngBryeZ5dBpvXr9cw_32, "Invalid matrix dimensions", 25);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_3QZA9aYngBryeZ5dBpvXr9cw_31 = {((NimStringDesc*) &TM_3QZA9aYngBryeZ5dBpvXr9cw_32)}
;

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation)(NI* x, NI y) {
	NI TM_3QZA9aYngBryeZ5dBpvXr9cw_4;
	nimfr_("*=", "system.nim");
	nimln_(3695, "system.nim");
	TM_3QZA9aYngBryeZ5dBpvXr9cw_4 = mulInt((*x), y);
	(*x) = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_4);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, exponent_binary_eqKG4APkqy5I3XN2s41dNw)(NI* n, NI* x) {
	NI result;
	NI res;
	nimfr_("exponent_binary", "exponentiation.nim");
{	result = (NI)0;
	nimln_(2, "exponentiation.nim");
	{
		NI z;
		NI T5_;
		NI TM_3QZA9aYngBryeZ5dBpvXr9cw_2;
		if (!((*x) < ((NI) 0))) goto LA3_;
		nimln_(3, "exponentiation.nim");
		if ((*x) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		z = ((NI64)-((*x)));
		nimln_(4, "exponentiation.nim");
		T5_ = (NI)0;
		T5_ = exponent_binary_eqKG4APkqy5I3XN2s41dNw(n, (&z));
		TM_3QZA9aYngBryeZ5dBpvXr9cw_2 = divInt(((NI) 1), T5_);
		result = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_2);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(5, "exponentiation.nim");
	res = ((NI) 1);
	{
		nimln_(6, "exponentiation.nim");
		while (1) {
			tyArray_sMpvt1sOxOJ3LFGulnbeMQ T12_;
			NI TM_3QZA9aYngBryeZ5dBpvXr9cw_7;
			if (!(((NI) 0) < (*x))) goto LA7;
			nimln_(7, "exponentiation.nim");
			{
				NI TM_3QZA9aYngBryeZ5dBpvXr9cw_3;
				TM_3QZA9aYngBryeZ5dBpvXr9cw_3 = modInt((*x), ((NI) 2));
				if (!((NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_3) == ((NI) 1))) goto LA10_;
				nimln_(8, "exponentiation.nim");
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation((&res), (*n));
			}
			LA10_: ;
			nimln_(9, "exponentiation.nim");
			memset((void*)T12_, 0, sizeof(T12_));
			T12_[0] = copyString(((NimStringDesc*) &TM_3QZA9aYngBryeZ5dBpvXr9cw_5));
			T12_[1] = nimIntToStr((*n));
			T12_[2] = copyString(((NimStringDesc*) &TM_3QZA9aYngBryeZ5dBpvXr9cw_6));
			T12_[3] = nimIntToStr((*x));
			echoBinSafe(T12_, 4);
			nimln_(10, "exponentiation.nim");
			stareq__tk9bwZBdb9bO9baUcUN2AX89bQexponentiation(n, (*n));
			nimln_(11, "exponentiation.nim");
			TM_3QZA9aYngBryeZ5dBpvXr9cw_7 = divInt((*x), ((NI) 2));
			(*x) = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_7);
		} LA7: ;
	}
	nimln_(12, "exponentiation.nim");
	result = res;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_IHUFRsFxZNv7YydiUO2esQ)(void* p, NI op) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* a;
	NI T1_;
	a = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, mult_mat_seq_gAx9cw1jGr5nn9cG9bQNBHmSw)(tySequence_IHUFRsFxZNv7YydiUO2esQ* x, tySequence_IHUFRsFxZNv7YydiUO2esQ* y) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* result;
	NI64 a;
	NI64 b;
	NI64 c;
	NI64 d;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_14;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_15;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_16;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_17;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_18;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_19;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_20;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_21;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_22;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_23;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_24;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_25;
	nimfr_("mult_mat_seq", "exponentiation.nim");
{	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	a = (NI64)0;
	b = (NI64)0;
	c = (NI64)0;
	d = (NI64)0;
	nimln_(19, "exponentiation.nim");
	{
		NI T3_;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_8;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_9;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_10;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_11;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_12;
		NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_13;
		T3_ = (y ? y->Sup.len : 0);
		if (!(T3_ == ((NI) 2))) goto LA4_;
		nimln_(20, "exponentiation.nim");
		if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_8 = mulInt64(x->data[((NI) 0)], y->data[((NI) 0)]);
		if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_9 = mulInt64(x->data[((NI) 1)], y->data[((NI) 1)]);
		TM_3QZA9aYngBryeZ5dBpvXr9cw_10 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_8), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_9));
		a = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_10);
		nimln_(21, "exponentiation.nim");
		if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_11 = mulInt64(x->data[((NI) 2)], y->data[((NI) 0)]);
		if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
		if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
		TM_3QZA9aYngBryeZ5dBpvXr9cw_12 = mulInt64(x->data[((NI) 3)], y->data[((NI) 1)]);
		TM_3QZA9aYngBryeZ5dBpvXr9cw_13 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_11), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_12));
		b = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_13);
		nimln_(22, "exponentiation.nim");
		result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*) newSeq((&NTI_IHUFRsFxZNv7YydiUO2esQ_), 2);
		result->data[0] = a;
		result->data[1] = b;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(23, "exponentiation.nim");
	if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_14 = mulInt64(x->data[((NI) 0)], y->data[((NI) 0)]);
	if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_15 = mulInt64(x->data[((NI) 1)], y->data[((NI) 2)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_16 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_14), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_15));
	a = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_16);
	nimln_(24, "exponentiation.nim");
	if ((NU)(((NI) 0)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_17 = mulInt64(x->data[((NI) 0)], y->data[((NI) 1)]);
	if ((NU)(((NI) 1)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_18 = mulInt64(x->data[((NI) 1)], y->data[((NI) 3)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_19 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_17), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_18));
	b = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_19);
	nimln_(25, "exponentiation.nim");
	if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 0)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_20 = mulInt64(x->data[((NI) 2)], y->data[((NI) 0)]);
	if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 2)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_21 = mulInt64(x->data[((NI) 3)], y->data[((NI) 2)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_22 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_20), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_21));
	c = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_22);
	nimln_(26, "exponentiation.nim");
	if ((NU)(((NI) 2)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 1)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_23 = mulInt64(x->data[((NI) 2)], y->data[((NI) 1)]);
	if ((NU)(((NI) 3)) >= (NU)(x->Sup.len)) raiseIndexError();
	if ((NU)(((NI) 3)) >= (NU)(y->Sup.len)) raiseIndexError();
	TM_3QZA9aYngBryeZ5dBpvXr9cw_24 = mulInt64(x->data[((NI) 3)], y->data[((NI) 3)]);
	TM_3QZA9aYngBryeZ5dBpvXr9cw_25 = addInt64((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_23), (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_24));
	d = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_25);
	nimln_(27, "exponentiation.nim");
	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*) newSeq((&NTI_IHUFRsFxZNv7YydiUO2esQ_), 4);
	result->data[0] = a;
	result->data[1] = b;
	result->data[2] = c;
	result->data[3] = d;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, modInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	{
		if (!(b == IL64(0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI64)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI64, divInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	{
		if (!(b == IL64(0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T7_)) goto LA8_;
		T7_ = (b == IL64(-1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI64)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, pow_mat_seq_r9aZSYkqxTNtselrdI83q7g)(tySequence_IHUFRsFxZNv7YydiUO2esQ** n, NI64* x) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* result;
	tySequence_IHUFRsFxZNv7YydiUO2esQ* res;
	nimfr_("pow_mat_seq", "exponentiation.nim");
{	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	res = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	nimln_(32, "exponentiation.nim");
	genericSeqAssign((&res), (*n), (&NTI_IHUFRsFxZNv7YydiUO2esQ_));
	{
		nimln_(33, "exponentiation.nim");
		while (1) {
			NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_27;
			if (!(IL64(0) < (*x))) goto LA2;
			nimln_(34, "exponentiation.nim");
			{
				NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_26;
				TM_3QZA9aYngBryeZ5dBpvXr9cw_26 = modInt64((*x), IL64(2));
				if (!((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_26) == IL64(1))) goto LA5_;
				nimln_(35, "exponentiation.nim");
				res = mult_mat_seq_gAx9cw1jGr5nn9cG9bQNBHmSw(res, (*n));
			}
			LA5_: ;
			nimln_(36, "exponentiation.nim");
			unsureAsgnRef((void**) (&(*n)), mult_mat_seq_gAx9cw1jGr5nn9cG9bQNBHmSw((*n), (*n)));
			nimln_(37, "exponentiation.nim");
			TM_3QZA9aYngBryeZ5dBpvXr9cw_27 = divInt64((*x), IL64(2));
			(*x) = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_27);
		} LA2: ;
	}
	nimln_(38, "exponentiation.nim");
	genericSeqAssign((&result), res, (&NTI_IHUFRsFxZNv7YydiUO2esQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, mult_mat_TwUb3trnSFHi9aXPb9buA3iA)(tyArray_X4Lo9adz49bWDIQMo8kGcUYA a, tyArray_X4Lo9adz49bWDIQMo8kGcUYA b, tyArray_X4Lo9adz49bWDIQMo8kGcUYA Result) {
	NI M;
	NI N;
	NI M2;
	NI N2;
	tyArray_X4Lo9adz49bWDIQMo8kGcUYA res;
	nimfr_("mult_mat", "exponentiation.nim");
{	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(41, "exponentiation.nim");
	M = ((NI) 2);
	nimln_(42, "exponentiation.nim");
	N = ((NI) 2);
	nimln_(43, "exponentiation.nim");
	M2 = ((NI) 2);
	nimln_(44, "exponentiation.nim");
	N2 = ((NI) 2);
	nimln_(45, "exponentiation.nim");
	{
		nimln_(398, "system.nim");
		nimln_(45, "exponentiation.nim");
		if (!!((M == N))) goto LA3_;
		nimln_(46, "exponentiation.nim");
		echoBinSafe(TM_3QZA9aYngBryeZ5dBpvXr9cw_31, 1);
	}
	LA3_: ;
	memset((void*)res, 0, sizeof(res));
	nimln_(47, "exponentiation.nim");
	memcpy((void*)res, (NIM_CONST void*)a, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3QZA9aYngBryeZ5dBpvXr9cw_34;
				if (!(i_2 < M)) goto LA7;
				nimln_(3521, "system.nim");
				i = i_2;
				{
					NI j;
					NI i_3;
					j = (NI)0;
					nimln_(3519, "system.nim");
					i_3 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_3QZA9aYngBryeZ5dBpvXr9cw_33;
							if (!(i_3 < N2)) goto LA10;
							nimln_(3521, "system.nim");
							j = i_3;
							if ((NU)(i) > (NU)(1)) raiseIndexError();
							if ((NU)(j) > (NU)(1)) raiseIndexError();
							nimln_(50, "exponentiation.nim");
							res[(i)- 0][(j)- 0] = IL64(0);
							nimln_(3522, "system.nim");
							TM_3QZA9aYngBryeZ5dBpvXr9cw_33 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_33);
						} LA10: ;
					}
				}
				TM_3QZA9aYngBryeZ5dBpvXr9cw_34 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_34);
			} LA7: ;
		}
	}
	{
		NI i_4;
		NI i_5;
		i_4 = (NI)0;
		nimln_(3519, "system.nim");
		i_5 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3QZA9aYngBryeZ5dBpvXr9cw_39;
				if (!(i_5 < M)) goto LA13;
				nimln_(3521, "system.nim");
				i_4 = i_5;
				{
					NI j_2;
					NI i_6;
					j_2 = (NI)0;
					nimln_(3519, "system.nim");
					i_6 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_3QZA9aYngBryeZ5dBpvXr9cw_38;
							if (!(i_6 < N2)) goto LA16;
							nimln_(3521, "system.nim");
							j_2 = i_6;
							{
								NI k;
								NI i_7;
								k = (NI)0;
								nimln_(3519, "system.nim");
								i_7 = ((NI) 0);
								{
									nimln_(3520, "system.nim");
									while (1) {
										NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_35;
										NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_36;
										NI TM_3QZA9aYngBryeZ5dBpvXr9cw_37;
										if (!(i_7 < N)) goto LA19;
										nimln_(3521, "system.nim");
										k = i_7;
										nimln_(54, "exponentiation.nim");
										if ((NU)(i_4) > (NU)(1)) raiseIndexError();
										if ((NU)(j_2) > (NU)(1)) raiseIndexError();
										if ((NU)(i_4) > (NU)(1)) raiseIndexError();
										if ((NU)(k) > (NU)(1)) raiseIndexError();
										if ((NU)(k) > (NU)(1)) raiseIndexError();
										if ((NU)(j_2) > (NU)(1)) raiseIndexError();
										TM_3QZA9aYngBryeZ5dBpvXr9cw_35 = mulInt64(a[(i_4)- 0][(k)- 0], b[(k)- 0][(j_2)- 0]);
										TM_3QZA9aYngBryeZ5dBpvXr9cw_36 = addInt64(res[(i_4)- 0][(j_2)- 0], (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_35));
										res[(i_4)- 0][(j_2)- 0] = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_36);
										nimln_(3522, "system.nim");
										TM_3QZA9aYngBryeZ5dBpvXr9cw_37 = addInt(i_7, ((NI) 1));
										i_7 = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_37);
									} LA19: ;
								}
							}
							TM_3QZA9aYngBryeZ5dBpvXr9cw_38 = addInt(i_6, ((NI) 1));
							i_6 = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_38);
						} LA16: ;
					}
				}
				TM_3QZA9aYngBryeZ5dBpvXr9cw_39 = addInt(i_5, ((NI) 1));
				i_5 = (NI)(TM_3QZA9aYngBryeZ5dBpvXr9cw_39);
			} LA13: ;
		}
	}
	nimln_(55, "exponentiation.nim");
	memcpy((void*)Result, (NIM_CONST void*)res, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pow_mat_HdAB07TCTeuAOvGfbnUtNw)(tyArray_EawPLnQhPqWwYm5GdCoh8A* a, NI64* x, tyArray_X4Lo9adz49bWDIQMo8kGcUYA Result) {
	tyArray_X4Lo9adz49bWDIQMo8kGcUYA res;
	nimfr_("pow_mat", "exponentiation.nim");
{	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	memset((void*)res, 0, sizeof(res));
	nimln_(58, "exponentiation.nim");
	memcpy((void*)res, (NIM_CONST void*)a, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	{
		nimln_(59, "exponentiation.nim");
		while (1) {
			tyArray_X4Lo9adz49bWDIQMo8kGcUYA T8_;
			NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_40;
			if (!(IL64(0) < (*x))) goto LA2;
			nimln_(60, "exponentiation.nim");
			{
				NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_30;
				tyArray_X4Lo9adz49bWDIQMo8kGcUYA T7_;
				TM_3QZA9aYngBryeZ5dBpvXr9cw_30 = modInt64((*x), IL64(2));
				if (!((NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_30) == IL64(1))) goto LA5_;
				nimln_(61, "exponentiation.nim");
				memset((void*)T7_, 0, sizeof(T7_));
				mult_mat_TwUb3trnSFHi9aXPb9buA3iA(res, a, T7_);
				memcpy((void*)res, (NIM_CONST void*)T7_, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
			}
			LA5_: ;
			nimln_(62, "exponentiation.nim");
			memset((void*)T8_, 0, sizeof(T8_));
			mult_mat_TwUb3trnSFHi9aXPb9buA3iA(a, a, T8_);
			memcpy((void*)a, (NIM_CONST void*)T8_, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
			nimln_(63, "exponentiation.nim");
			TM_3QZA9aYngBryeZ5dBpvXr9cw_40 = divInt64((*x), IL64(2));
			(*x) = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_40);
		} LA2: ;
	}
	nimln_(64, "exponentiation.nim");
	memcpy((void*)Result, (NIM_CONST void*)res, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI64, fib_matrix_exp_qSFrKVtQsOuIF1VV39aezJQ)(NI64 n) {
	NI64 result;
	tyArray_X4Lo9adz49bWDIQMo8kGcUYA A;
	NI64 x;
	NI64 TM_3QZA9aYngBryeZ5dBpvXr9cw_29;
	tyArray_X4Lo9adz49bWDIQMo8kGcUYA T1_;
	nimfr_("fib_matrix_exp", "exponentiation.nim");
{	result = (NI64)0;
	memset((void*)A, 0, sizeof(A));
	nimln_(69, "exponentiation.nim");
	memcpy((void*)A, (NIM_CONST void*)TM_3QZA9aYngBryeZ5dBpvXr9cw_28, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	x = (NI64)0;
	nimln_(71, "exponentiation.nim");
	TM_3QZA9aYngBryeZ5dBpvXr9cw_29 = subInt64(n, IL64(2));
	x = (NI64)(TM_3QZA9aYngBryeZ5dBpvXr9cw_29);
	nimln_(72, "exponentiation.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	pow_mat_HdAB07TCTeuAOvGfbnUtNw(A, (&x), T1_);
	memcpy((void*)A, (NIM_CONST void*)T1_, sizeof(tyArray_X4Lo9adz49bWDIQMo8kGcUYA));
	nimln_(73, "exponentiation.nim");
	result = A[(((NI) 0))- 0][(((NI) 0))- 0];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	exponentiationDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI T2_;
	nimfr_("exponentiation", "exponentiation.nim");
	nimln_(75, "exponentiation.nim");
	x_4lJzM9awleS2bOq9bPStf9bpw = ((NI) 2);
	nimln_(76, "exponentiation.nim");
	y_M4Xr9cr2hdldN4ghM59b0i3g = ((NI) 5);
	nimln_(77, "exponentiation.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NI)0;
	T2_ = exponent_binary_eqKG4APkqy5I3XN2s41dNw((&x_4lJzM9awleS2bOq9bPStf9bpw), (&y_M4Xr9cr2hdldN4ghM59b0i3g));
	T1_[0] = nimIntToStr(T2_);
	echoBinSafe(T1_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, exponentiationDatInit000)(void) {
NTI_IHUFRsFxZNv7YydiUO2esQ_.size = sizeof(tySequence_IHUFRsFxZNv7YydiUO2esQ*);
NTI_IHUFRsFxZNv7YydiUO2esQ_.kind = 24;
NTI_IHUFRsFxZNv7YydiUO2esQ_.base = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
NTI_IHUFRsFxZNv7YydiUO2esQ_.flags = 2;
NTI_IHUFRsFxZNv7YydiUO2esQ_.marker = Marker_tySequence_IHUFRsFxZNv7YydiUO2esQ;
}

