/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\aisae\Documents\Dependencies\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\Users\aisae\Documents\Dependencies\nim-0.18.0\lib -o c:\Users\aisae\Documents\Sourcetree\Challenges\Nim\nimcache\fibonacci.o c:\Users\aisae\Documents\Sourcetree\Challenges\Nim\nimcache\fibonacci.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_IHUFRsFxZNv7YydiUO2esQ tySequence_IHUFRsFxZNv7YydiUO2esQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tySequence_IHUFRsFxZNv7YydiUO2esQ {
  TGenericSeq Sup;
  NI64 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, prime_factorize_9btfSQmAdKV2xmhyxQPgcMw)(NI64 n);
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, newSeq_K4uiYKl7aEFNrk8kJo7BtQ)(NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__0b4ekXvToMcMODtKTiwn1A)(tySequence_IHUFRsFxZNv7YydiUO2esQ* x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NI64, modInt64)(NI64 a, NI64 b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, fib_seq_XazPuNBjdSNg3uZwoGbpzA)(NI64 n);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI64, pisano_period_9b9a7ssqgv9ay536xNiwlX8gA)(NI64 m);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI64, fib_mod_m_tPwH6fOJ62ma2JW479bsx6A)(NI64 n, NI64 m);
N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, fib_mod_seq_U2MJiqn86qSPWlDy4jAekA)(NI64 n, NI64 m);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString_9cUgpFExghz2xc7T9aS9cYsUQ)(tySequence_IHUFRsFxZNv7YydiUO2esQ* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_OZ3WzoMLDLYdJ875pkutmA)(NimStringDesc** s, NI64 x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, fibonacciDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_IHUFRsFxZNv7YydiUO2esQ_;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI64, modInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	{
		if (!(b == IL64(0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI64)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, prime_factorize_9btfSQmAdKV2xmhyxQPgcMw)(NI64 n) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* result;
	tySequence_IHUFRsFxZNv7YydiUO2esQ* prime_factors;
	NI n_sqrt;
	NF T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	NI64 temp_n;
	NI64 i_2;
	nimfr_("prime_factorize", "fibonacci.nim");
{	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	nimln_(5, "fibonacci.nim");
	prime_factors = newSeq_K4uiYKl7aEFNrk8kJo7BtQ(((NI) 0));
	nimln_(6, "fibonacci.nim");
	T1_ = (NF)0;
	T1_ = sqrt(((NF) (n)));
	n_sqrt = ((NI) (T1_));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI T5_;
				NI TM_Vgl9cfKragMtnbvBdG1w9aow_2;
				if (!(res <= n_sqrt)) goto LA4;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(8, "fibonacci.nim");
				prime_factors = (tySequence_IHUFRsFxZNv7YydiUO2esQ*) incrSeqV2(&(prime_factors)->Sup, sizeof(NI));
				T5_ = prime_factors->Sup.len++;
				prime_factors->data[T5_] = ((NI) 0);
				nimln_(2048, "system.nim");
				TM_Vgl9cfKragMtnbvBdG1w9aow_2 = addInt(res, ((NI) 1));
				res = (NI)(TM_Vgl9cfKragMtnbvBdG1w9aow_2);
			} LA4: ;
		}
	}
	nimln_(10, "fibonacci.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	T6_[0] = dollar__0b4ekXvToMcMODtKTiwn1A(prime_factors);
	echoBinSafe(T6_, 1);
	{
		nimln_(12, "fibonacci.nim");
		while (1) {
			NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_3;
			NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_4;
			TM_Vgl9cfKragMtnbvBdG1w9aow_3 = modInt64(n, IL64(2));
			if (!((NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_3) == IL64(0))) goto LA8;
			nimln_(13, "fibonacci.nim");
			if ((NU)(((NI) 2)) >= (NU)(prime_factors->Sup.len)) raiseIndexError();
			TM_Vgl9cfKragMtnbvBdG1w9aow_4 = addInt64(prime_factors->data[((NI) 2)], ((NI) 1));
			prime_factors->data[((NI) 2)] = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_4);
		} LA8: ;
	}
	nimln_(15, "fibonacci.nim");
	temp_n = n;
	i_2 = (NI64)0;
	nimln_(17, "fibonacci.nim");
	i_2 = IL64(3);
	{
		nimln_(18, "fibonacci.nim");
		while (1) {
			NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_7;
			if (!(i_2 <= ((NI64) (n_sqrt)))) goto LA10;
			{
				nimln_(19, "fibonacci.nim");
				while (1) {
					NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_5;
					NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_6;
					NF T13_;
					TM_Vgl9cfKragMtnbvBdG1w9aow_5 = modInt64(temp_n, i_2);
					if (!((NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_5) == IL64(0))) goto LA12;
					nimln_(20, "fibonacci.nim");
					if ((NU)(i_2) >= (NU)(prime_factors->Sup.len)) raiseIndexError();
					TM_Vgl9cfKragMtnbvBdG1w9aow_6 = addInt64(prime_factors->data[i_2], ((NI) 1));
					prime_factors->data[i_2] = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_6);
					nimln_(21, "fibonacci.nim");
					T13_ = (NF)0;
					T13_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(((NI) (temp_n)), ((NI) (i_2)));
					temp_n = ((NI64) (T13_));
				} LA12: ;
			}
			nimln_(22, "fibonacci.nim");
			TM_Vgl9cfKragMtnbvBdG1w9aow_7 = addInt64(i_2, ((NI) 2));
			i_2 = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_7);
		} LA10: ;
	}
	nimln_(23, "fibonacci.nim");
	genericSeqAssign((&result), prime_factors, (&NTI_IHUFRsFxZNv7YydiUO2esQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, fib_seq_XazPuNBjdSNg3uZwoGbpzA)(NI64 n) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* result;
	NI64 a;
	NI64 b;
	NI64 temp;
	tySequence_IHUFRsFxZNv7YydiUO2esQ* f_seq;
	NI T1_;
	nimfr_("fib_seq", "fibonacci.nim");
{	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	a = (NI64)0;
	b = (NI64)0;
	temp = (NI64)0;
	nimln_(27, "fibonacci.nim");
	f_seq = newSeq_K4uiYKl7aEFNrk8kJo7BtQ(((NI) 0));
	nimln_(28, "fibonacci.nim");
	f_seq = (tySequence_IHUFRsFxZNv7YydiUO2esQ*) incrSeqV2(&(f_seq)->Sup, sizeof(NI));
	T1_ = f_seq->Sup.len++;
	f_seq->data[T1_] = ((NI) 0);
	nimln_(29, "fibonacci.nim");
	{
		nimln_(398, "system.nim");
		nimln_(29, "fibonacci.nim");
		if (!!((n == IL64(0)))) goto LA4_;
		nimln_(30, "fibonacci.nim");
		a = IL64(0);
		nimln_(31, "fibonacci.nim");
		b = IL64(1);
		{
			NI64 i;
			NI64 colontmp_;
			NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_8;
			NI64 res;
			i = (NI64)0;
			colontmp_ = (NI64)0;
			nimln_(32, "fibonacci.nim");
			TM_Vgl9cfKragMtnbvBdG1w9aow_8 = subInt64(n, ((NI) 1));
			colontmp_ = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_8);
			nimln_(2059, "system.nim");
			res = IL64(1);
			{
				nimln_(2060, "system.nim");
				while (1) {
					NI T9_;
					NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_9;
					NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_10;
					if (!(res <= colontmp_)) goto LA8;
					nimln_(2061, "system.nim");
					i = res;
					nimln_(33, "fibonacci.nim");
					f_seq = (tySequence_IHUFRsFxZNv7YydiUO2esQ*) incrSeqV2(&(f_seq)->Sup, sizeof(NI64));
					T9_ = f_seq->Sup.len++;
					f_seq->data[T9_] = b;
					nimln_(34, "fibonacci.nim");
					temp = b;
					nimln_(35, "fibonacci.nim");
					TM_Vgl9cfKragMtnbvBdG1w9aow_9 = addInt64(a, b);
					b = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_9);
					nimln_(36, "fibonacci.nim");
					a = temp;
					nimln_(2062, "system.nim");
					TM_Vgl9cfKragMtnbvBdG1w9aow_10 = addInt64(res, ((NI) 1));
					res = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_10);
				} LA8: ;
			}
		}
	}
	LA4_: ;
	nimln_(37, "fibonacci.nim");
	genericSeqAssign((&result), f_seq, (&NTI_IHUFRsFxZNv7YydiUO2esQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, pisano_period_9b9a7ssqgv9ay536xNiwlX8gA)(NI64 m) {
	NI64 result;
	NI64 a;
	NI64 b;
	NI64 temp;
	NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_11;
	nimfr_("pisano_period", "fibonacci.nim");
{	result = (NI64)0;
	a = (NI64)0;
	b = (NI64)0;
	temp = (NI64)0;
	nimln_(41, "fibonacci.nim");
	a = IL64(0);
	nimln_(42, "fibonacci.nim");
	b = IL64(1);
	nimln_(43, "fibonacci.nim");
	TM_Vgl9cfKragMtnbvBdG1w9aow_11 = addInt64(a, b);
	temp = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_11);
	{
		NI64 i;
		NI64 colontmp_;
		NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_12;
		NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_13;
		NI64 res;
		i = (NI64)0;
		colontmp_ = (NI64)0;
		nimln_(44, "fibonacci.nim");
		TM_Vgl9cfKragMtnbvBdG1w9aow_12 = mulInt64(m, m);
		TM_Vgl9cfKragMtnbvBdG1w9aow_13 = subInt64((NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_12), ((NI) 1));
		colontmp_ = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_13);
		nimln_(2059, "system.nim");
		res = IL64(0);
		{
			nimln_(2060, "system.nim");
			while (1) {
				NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_14;
				NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_15;
				NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_17;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2061, "system.nim");
				i = res;
				nimln_(45, "fibonacci.nim");
				TM_Vgl9cfKragMtnbvBdG1w9aow_14 = addInt64(a, b);
				TM_Vgl9cfKragMtnbvBdG1w9aow_15 = modInt64((NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_14), m);
				temp = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_15);
				nimln_(46, "fibonacci.nim");
				a = b;
				nimln_(47, "fibonacci.nim");
				b = temp;
				nimln_(48, "fibonacci.nim");
				{
					NIM_BOOL T6_;
					NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_16;
					T6_ = (NIM_BOOL)0;
					T6_ = (a == IL64(0));
					if (!(T6_)) goto LA7_;
					T6_ = (b == IL64(1));
					LA7_: ;
					if (!T6_) goto LA8_;
					nimln_(49, "fibonacci.nim");
					TM_Vgl9cfKragMtnbvBdG1w9aow_16 = addInt64(i, IL64(1));
					result = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_16);
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(2062, "system.nim");
				TM_Vgl9cfKragMtnbvBdG1w9aow_17 = addInt64(res, ((NI) 1));
				res = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_17);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, fib_mod_m_tPwH6fOJ62ma2JW479bsx6A)(NI64 n, NI64 m) {
	NI64 result;
	NI64 pisano_length;
	NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_18;
	nimfr_("fib_mod_m", "fibonacci.nim");
{	result = (NI64)0;
	pisano_length = (NI64)0;
	nimln_(53, "fibonacci.nim");
	pisano_length = pisano_period_9b9a7ssqgv9ay536xNiwlX8gA(m);
	nimln_(54, "fibonacci.nim");
	TM_Vgl9cfKragMtnbvBdG1w9aow_18 = modInt64(n, pisano_length);
	result = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_18);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_IHUFRsFxZNv7YydiUO2esQ*, fib_mod_seq_U2MJiqn86qSPWlDy4jAekA)(NI64 n, NI64 m) {
	tySequence_IHUFRsFxZNv7YydiUO2esQ* result;
	NI64 a;
	NI64 b;
	NI64 temp;
	tySequence_IHUFRsFxZNv7YydiUO2esQ* f_seq;
	nimfr_("fib_mod_seq", "fibonacci.nim");
{	result = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	a = (NI64)0;
	b = (NI64)0;
	temp = (NI64)0;
	nimln_(58, "fibonacci.nim");
	f_seq = fib_seq_XazPuNBjdSNg3uZwoGbpzA(n);
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(59, "fibonacci.nim");
		T2_ = (f_seq ? f_seq->Sup.len : 0);
		colontmp_ = T2_;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI64 TM_Vgl9cfKragMtnbvBdG1w9aow_19;
				NI TM_Vgl9cfKragMtnbvBdG1w9aow_20;
				if (!(i_2 < colontmp_)) goto LA4;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) >= (NU)(f_seq->Sup.len)) raiseIndexError();
				nimln_(60, "fibonacci.nim");
				if ((NU)(i) >= (NU)(f_seq->Sup.len)) raiseIndexError();
				TM_Vgl9cfKragMtnbvBdG1w9aow_19 = modInt64(f_seq->data[i], m);
				f_seq->data[i] = (NI64)(TM_Vgl9cfKragMtnbvBdG1w9aow_19);
				nimln_(3522, "system.nim");
				TM_Vgl9cfKragMtnbvBdG1w9aow_20 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_Vgl9cfKragMtnbvBdG1w9aow_20);
			} LA4: ;
		}
	}
	nimln_(61, "fibonacci.nim");
	genericSeqAssign((&result), f_seq, (&NTI_IHUFRsFxZNv7YydiUO2esQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	fibonacciDatInit000();
	stdlib_mathInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	tySequence_IHUFRsFxZNv7YydiUO2esQ* T2_;
	nimfr_("fibonacci", "fibonacci.nim");
	nimln_(67, "fibonacci.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (tySequence_IHUFRsFxZNv7YydiUO2esQ*)0;
	T2_ = prime_factorize_9btfSQmAdKV2xmhyxQPgcMw(IL64(2015));
	T1_[0] = dollar__0b4ekXvToMcMODtKTiwn1A(T2_);
	echoBinSafe(T1_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, fibonacciDatInit000)(void) {
}

