/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   D:\Documents\Code\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing  -ID:\Documents\Code\nim-0.18.0\lib -o d:\Documents\SourceTree\Challenges\Nim\nimcache\riceballs.o d:\Documents\SourceTree\Challenges\Nim\nimcache\riceballs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NI tyArray_gPxHo5syoDE5Owh2dUZmBQ[401];
typedef tyArray_gPxHo5syoDE5Owh2dUZmBQ tyArray_IAUdws7KOIawZ9bQltuvQbw[401];
struct tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg {
  RootObj Sup;
NI colonstate_;
tyArray_IAUdws7KOIawZ9bQltuvQbw dp1;
tyArray_gPxHo5syoDE5Owh2dUZmBQ balls2;
tyArray_gPxHo5syoDE5Owh2dUZmBQ sums3;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NI i, NI j, void* ClE_0);
void* ClE_0;
} tyProc_fDD7zVPPl59bNBu4ChTEQeQ;
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_5) (NI i, NI j);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_6) (NI i, NI j);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_7) (NI l, NI r);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_8) (NI l, NI r);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_9) (NI l, NI r);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_10) (NI l, NI r);
typedef N_CLOSURE_PTR(NI, TM_PBeNFxZ5kba7NlPpOcYYfA_11) (NI i, NI j);
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, reopen_zvZzxj8muVg8NFhMoIXl9ag)(FILE* f, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode);
N_LIB_PRIVATE N_NIMCALL(NF, ntcpuTime)(void);
N_LIB_PRIVATE N_NIMCALL(void, Run_XNvl3groTIoQOj0Z9cenuIQ)(void);
static N_NIMCALL(void, Marker_tyRef_9as2N19a1eEcxS9afXVHxHztQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw seps, NI maxsplit);
N_LIB_PRIVATE N_CLOSURE(NI, search_FrT2y2c1niLZHzZZVe350g)(NI l, NI r, void* ClE_0);
N_LIB_PRIVATE N_CLOSURE(NI, getR_Vo9bV9ahXp7c8PRLqslK6xtg)(NI i, NI j, void* ClE_0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, riceballsDatInit000)(void);
NF startTime_neFSLFytAifhxDDHWSDdhA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_s9alDn6SkiHPWU48XI85epg_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_gPxHo5syoDE5Owh2dUZmBQ_;
TNimType NTI_IAUdws7KOIawZ9bQltuvQbw_;
TNimType NTI_9as2N19a1eEcxS9afXVHxHztQ_;
NF endTime_Pifgz3zkL0Z9b2QEisvxS3Q;
STRING_LITERAL(TM_PBeNFxZ5kba7NlPpOcYYfA_2, "input.txt", 9);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_PBeNFxZ5kba7NlPpOcYYfA_4 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_PBeNFxZ5kba7NlPpOcYYfA_12, "Duration: ", 10);
static N_NIMCALL(void, Marker_tyRef_9as2N19a1eEcxS9afXVHxHztQ)(void* p, NI op) {
	tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg* a;
	NI T1_;
	NI T2_;
	NI T3_;
	NI T4_;
	a = (tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 401; T1_++) {
	T2_ = (NI)0;
	}
	T3_ = (NI)0;
	T4_ = (NI)0;
}

N_LIB_PRIVATE N_CLOSURE(NI, getR_Vo9bV9ahXp7c8PRLqslK6xtg)(NI i, NI j, void* ClE_0) {
	NI result;
	tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg* colonenvP_;
{	result = (NI)0;
	colonenvP_ = (tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*) ClE_0;
	{
		if (!(i == j)) goto LA3_;
		result = (*colonenvP_).balls2[(i)- 0];
		goto BeforeRet_;
	}
	LA3_: ;
	result = (NI)((*colonenvP_).sums3[(j)- 0] - (*colonenvP_).sums3[((NI)(i - ((NI) 1)))- 0]);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_CLOSURE(NI, search_FrT2y2c1niLZHzZZVe350g)(NI l, NI r, void* ClE_0) {
	NI result;
	tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg* colonenvP_;
{	result = (NI)0;
	colonenvP_ = (tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*) ClE_0;
	{
		NI val;
		if (!((*colonenvP_).dp1[(l)- 0][(r)- 0] == ((NI) 0))) goto LA3_;
		val = ((NI) -1);
		{
			if (!(r <= l)) goto LA7_;
			val = ((NI) 1);
		}
		goto LA5_;
		LA7_: ;
		{
			NI i;
			NI j;
			i = l;
			j = r;
			{
				while (1) {
					NI lsum;
					tyProc_fDD7zVPPl59bNBu4ChTEQeQ T12_;
					NI rsum;
					tyProc_fDD7zVPPl59bNBu4ChTEQeQ T13_;
					if (!(i < j)) goto LA11;
					memset((void*)(&T12_), 0, sizeof(T12_));
					T12_.ClP_0 = getR_Vo9bV9ahXp7c8PRLqslK6xtg; T12_.ClE_0 = colonenvP_;
					lsum = T12_.ClE_0? T12_.ClP_0(l, i, T12_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_5)(T12_.ClP_0))(l, i);
					memset((void*)(&T13_), 0, sizeof(T13_));
					T13_.ClP_0 = getR_Vo9bV9ahXp7c8PRLqslK6xtg; T13_.ClE_0 = colonenvP_;
					rsum = T13_.ClE_0? T13_.ClP_0(j, r, T13_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_6)(T13_.ClP_0))(j, r);
					{
						if (!(lsum < rsum)) goto LA16_;
						i += ((NI) 1);
					}
					goto LA14_;
					LA16_: ;
					{
						if (!(rsum < lsum)) goto LA19_;
						j -= ((NI) 1);
					}
					goto LA14_;
					LA19_: ;
					{
						{
							NIM_BOOL T24_;
							NIM_BOOL T25_;
							tyProc_fDD7zVPPl59bNBu4ChTEQeQ T26_;
							NI T27_;
							tyProc_fDD7zVPPl59bNBu4ChTEQeQ T29_;
							NI T30_;
							tyProc_fDD7zVPPl59bNBu4ChTEQeQ T32_;
							NI T33_;
							T24_ = (NIM_BOOL)0;
							T25_ = (NIM_BOOL)0;
							memset((void*)(&T26_), 0, sizeof(T26_));
							T26_.ClP_0 = search_FrT2y2c1niLZHzZZVe350g; T26_.ClE_0 = colonenvP_;
							T27_ = (NI)0;
							T27_ = T26_.ClE_0? T26_.ClP_0(l, i, T26_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_7)(T26_.ClP_0))(l, i);
							T25_ = (T27_ == ((NI) 1));
							if (!(T25_)) goto LA28_;
							memset((void*)(&T29_), 0, sizeof(T29_));
							T29_.ClP_0 = search_FrT2y2c1niLZHzZZVe350g; T29_.ClE_0 = colonenvP_;
							T30_ = (NI)0;
							T30_ = T29_.ClE_0? T29_.ClP_0((NI)(i + ((NI) 1)), (NI)(j - ((NI) 1)), T29_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_8)(T29_.ClP_0))((NI)(i + ((NI) 1)), (NI)(j - ((NI) 1)));
							T25_ = (T30_ == ((NI) 1));
							LA28_: ;
							T24_ = T25_;
							if (!(T24_)) goto LA31_;
							memset((void*)(&T32_), 0, sizeof(T32_));
							T32_.ClP_0 = search_FrT2y2c1niLZHzZZVe350g; T32_.ClE_0 = colonenvP_;
							T33_ = (NI)0;
							T33_ = T32_.ClE_0? T32_.ClP_0(j, r, T32_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_9)(T32_.ClP_0))(j, r);
							T24_ = (T33_ == ((NI) 1));
							LA31_: ;
							if (!T24_) goto LA34_;
							val = ((NI) 1);
							goto LA10;
						}
						LA34_: ;
						i += ((NI) 1);
						j -= ((NI) 1);
					}
					LA14_: ;
				} LA11: ;
			} LA10: ;
		}
		LA5_: ;
		(*colonenvP_).dp1[(l)- 0][(r)- 0] = val;
	}
	LA3_: ;
	result = (*colonenvP_).dp1[(l)- 0][(r)- 0];
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, Run_XNvl3groTIoQOj0Z9cenuIQ)(void) {
	tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg* colonenv_;
	NI n;
	NimStringDesc* T1_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* inp;
	NimStringDesc* T2_;
	NI ans;
	tyArray_nHXaesL0DJZHyVS07ARPRA T20_;
	colonenv_ = (tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*)0;
	colonenv_ = (tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*) newObj((&NTI_9as2N19a1eEcxS9afXVHxHztQ_), sizeof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg));
	(*colonenv_).Sup.m_type = (&NTI_s9alDn6SkiHPWU48XI85epg_);
	T1_ = (NimStringDesc*)0;
	T1_ = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	n = nsuParseInt(T1_);
	T2_ = (NimStringDesc*)0;
	T2_ = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	inp = nsuSplitCharSet(T2_, TM_PBeNFxZ5kba7NlPpOcYYfA_4, ((NI) -1));
	ans = ((NI) 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 1);
		{
			while (1) {
				if (!(res <= n)) goto LA5;
				i = res;
				(*colonenv_).balls2[(i)- 0] = nsuParseInt(inp->data[(NI)(i - ((NI) 1))]);
				(*colonenv_).sums3[(i)- 0] = (NI)((*colonenv_).sums3[((NI)(i - ((NI) 1)))- 0] + (*colonenv_).balls2[(i)- 0]);
				res += ((NI) 1);
			} LA5: ;
		}
	}
	{
		NI i_2;
		NI res_2;
		i_2 = (NI)0;
		res_2 = ((NI) 1);
		{
			while (1) {
				if (!(res_2 <= n)) goto LA8;
				i_2 = res_2;
				{
					NI j;
					NI res_3;
					j = (NI)0;
					res_3 = i_2;
					{
						while (1) {
							if (!(res_3 <= n)) goto LA11;
							j = res_3;
							{
								tyProc_fDD7zVPPl59bNBu4ChTEQeQ T14_;
								NI T15_;
								tyProc_fDD7zVPPl59bNBu4ChTEQeQ T18_;
								NI T19_;
								memset((void*)(&T14_), 0, sizeof(T14_));
								T14_.ClP_0 = search_FrT2y2c1niLZHzZZVe350g; T14_.ClE_0 = colonenv_;
								T15_ = (NI)0;
								T15_ = T14_.ClE_0? T14_.ClP_0(i_2, j, T14_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_10)(T14_.ClP_0))(i_2, j);
								if (!(T15_ == ((NI) 1))) goto LA16_;
								memset((void*)(&T18_), 0, sizeof(T18_));
								T18_.ClP_0 = getR_Vo9bV9ahXp7c8PRLqslK6xtg; T18_.ClE_0 = colonenv_;
								T19_ = (NI)0;
								T19_ = T18_.ClE_0? T18_.ClP_0(i_2, j, T18_.ClE_0):((TM_PBeNFxZ5kba7NlPpOcYYfA_11)(T18_.ClP_0))(i_2, j);
								ans = ((ans >= T19_) ? ans : T19_);
							}
							LA16_: ;
							res_3 += ((NI) 1);
						} LA11: ;
					}
				}
				res_2 += ((NI) 1);
			} LA8: ;
		}
	}
	memset((void*)T20_, 0, sizeof(T20_));
	T20_[0] = nimIntToStr(ans);
	echoBinSafe(T20_, 1);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	riceballsDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NIM_BOOL T1_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T2_;
	T1_ = (NIM_BOOL)0;
	T1_ = reopen_zvZzxj8muVg8NFhMoIXl9ag(stdin, ((NimStringDesc*) &TM_PBeNFxZ5kba7NlPpOcYYfA_2), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0));
	T1_;
	startTime_neFSLFytAifhxDDHWSDdhA = ntcpuTime();
	Run_XNvl3groTIoQOj0Z9cenuIQ();
	endTime_Pifgz3zkL0Z9b2QEisvxS3Q = ntcpuTime();
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = copyString(((NimStringDesc*) &TM_PBeNFxZ5kba7NlPpOcYYfA_12));
	T2_[1] = nimFloatToStr(((NF)(endTime_Pifgz3zkL0Z9b2QEisvxS3Q) - (NF)(startTime_neFSLFytAifhxDDHWSDdhA)));
	echoBinSafe(T2_, 2);
}

NIM_EXTERNC N_NOINLINE(void, riceballsDatInit000)(void) {
static TNimNode* TM_PBeNFxZ5kba7NlPpOcYYfA_3[4];
static TNimNode TM_PBeNFxZ5kba7NlPpOcYYfA_0[5];
NTI_s9alDn6SkiHPWU48XI85epg_.size = sizeof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg);
NTI_s9alDn6SkiHPWU48XI85epg_.kind = 17;
NTI_s9alDn6SkiHPWU48XI85epg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_s9alDn6SkiHPWU48XI85epg_.flags = 1;
TM_PBeNFxZ5kba7NlPpOcYYfA_3[0] = &TM_PBeNFxZ5kba7NlPpOcYYfA_0[1];
TM_PBeNFxZ5kba7NlPpOcYYfA_0[1].kind = 1;
TM_PBeNFxZ5kba7NlPpOcYYfA_0[1].offset = offsetof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg, colonstate_);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[1].name = ":state";
TM_PBeNFxZ5kba7NlPpOcYYfA_3[1] = &TM_PBeNFxZ5kba7NlPpOcYYfA_0[2];
NTI_gPxHo5syoDE5Owh2dUZmBQ_.size = sizeof(tyArray_gPxHo5syoDE5Owh2dUZmBQ);
NTI_gPxHo5syoDE5Owh2dUZmBQ_.kind = 16;
NTI_gPxHo5syoDE5Owh2dUZmBQ_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_gPxHo5syoDE5Owh2dUZmBQ_.flags = 3;
NTI_IAUdws7KOIawZ9bQltuvQbw_.size = sizeof(tyArray_IAUdws7KOIawZ9bQltuvQbw);
NTI_IAUdws7KOIawZ9bQltuvQbw_.kind = 16;
NTI_IAUdws7KOIawZ9bQltuvQbw_.base = (&NTI_gPxHo5syoDE5Owh2dUZmBQ_);
NTI_IAUdws7KOIawZ9bQltuvQbw_.flags = 3;
TM_PBeNFxZ5kba7NlPpOcYYfA_0[2].kind = 1;
TM_PBeNFxZ5kba7NlPpOcYYfA_0[2].offset = offsetof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg, dp1);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[2].typ = (&NTI_IAUdws7KOIawZ9bQltuvQbw_);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[2].name = "dp1";
TM_PBeNFxZ5kba7NlPpOcYYfA_3[2] = &TM_PBeNFxZ5kba7NlPpOcYYfA_0[3];
TM_PBeNFxZ5kba7NlPpOcYYfA_0[3].kind = 1;
TM_PBeNFxZ5kba7NlPpOcYYfA_0[3].offset = offsetof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg, balls2);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[3].typ = (&NTI_gPxHo5syoDE5Owh2dUZmBQ_);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[3].name = "balls2";
TM_PBeNFxZ5kba7NlPpOcYYfA_3[3] = &TM_PBeNFxZ5kba7NlPpOcYYfA_0[4];
TM_PBeNFxZ5kba7NlPpOcYYfA_0[4].kind = 1;
TM_PBeNFxZ5kba7NlPpOcYYfA_0[4].offset = offsetof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg, sums3);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[4].typ = (&NTI_gPxHo5syoDE5Owh2dUZmBQ_);
TM_PBeNFxZ5kba7NlPpOcYYfA_0[4].name = "sums3";
TM_PBeNFxZ5kba7NlPpOcYYfA_0[0].len = 4; TM_PBeNFxZ5kba7NlPpOcYYfA_0[0].kind = 2; TM_PBeNFxZ5kba7NlPpOcYYfA_0[0].sons = &TM_PBeNFxZ5kba7NlPpOcYYfA_3[0];
NTI_s9alDn6SkiHPWU48XI85epg_.node = &TM_PBeNFxZ5kba7NlPpOcYYfA_0[0];
NTI_9as2N19a1eEcxS9afXVHxHztQ_.size = sizeof(tyObject_Env_riceballsdotnim__s9alDn6SkiHPWU48XI85epg*);
NTI_9as2N19a1eEcxS9afXVHxHztQ_.kind = 22;
NTI_9as2N19a1eEcxS9afXVHxHztQ_.base = (&NTI_s9alDn6SkiHPWU48XI85epg_);
NTI_9as2N19a1eEcxS9afXVHxHztQ_.marker = Marker_tyRef_9as2N19a1eEcxS9afXVHxHztQ;
}

